## **Theoretical Foundation:**
The Dirichlet distribution operates as a multivariate generalization of the Beta distribution.  
Instead of generating a single probability bounded between 0 and 1, it generates an entire probability   
vector $\mathbf{x} = (x_1, \dots, x_k)$ mapped to a $K$-dimensional simplex, where all variables sum exactly to 1

$$f(x_1, \dots, x_k) \propto \prod_{i=1}^k x_i^{\alpha_i - 1}$$

In [2]:
import numpy as  np
import matplotlib.pyplot as plt
from scipy.stats import dirichlet

alpha_dir = [2.0, 3.0, 5.0]
dist_dir = dirichlet(alpha=alpha_dir)

# Draw multiple samples representing probability vectors
samples_dir = dist_dir.rvs(size=3)
print("Dirichlet Probability Vectors (each row sums to 1):")
print(samples_dir)

Dirichlet Probability Vectors (each row sums to 1):
[[0.32605928 0.1117612  0.56217952]
 [0.31008415 0.25585347 0.43406239]
 [0.07896757 0.37283421 0.54819822]]


## **Practical Application:**
It is the absolute core of machine learning Topic Modeling algorithms, specifically  
Latent Dirichlet Allocation (LDA). In LDA, the Dirichlet distribution functions as a hierarchical  
"distribution of distributions", continuously spawning underlying probability frameworks that   
map words to specific thematic topics.**

## **Interesting Fact:**
Because the sum of the variables must strictly equal 1, the Dirichlet distribution technically  
exists in $K-1$ dimensions despite having $K$ components. It serves as the mathematical conjugate  
prior to the Multinomial distribution, enabling highly optimized, closed-form Bayesian updates for machine learning.